[package]
name = "aiagents"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
phf =  { version = "0.14", features = ["macros"] }

# -- for webserver
ureq = { version = "3.3", features = ["json"] }

# -- for directory scanning
struct_extractors = { version = "0.1.0", git = "https://github.com/witold-k/struct_extractors" }
fsscanner = { version = "0.3.0", git = "https://github.com/witold-k/fsscanner" }

# -- process
ctrlc = "3.5.2"

