current_dir      := justfile_directory()
module_name      := file_name(current_dir)
target_dir       := 'target'

default: build

config: clean
    cmake -S . -B {{target_dir}} -G ninja

build:
    cmake --build {{target_dir}}

fix:
    git checkout .
    aifix -l cpp -t fix_code -f {{current_dir}} -f {{current_dir}}/..

fixd:
    git checkout .
    aifix -d -l cpp -t fix_code -f {{current_dir}} -f {{current_dir}}/..

fixws:
    git checkout .
    aifix -l cpp -t fix_code -w ~/svn/_workspace -f {{current_dir}} -f {{current_dir}}/.. -f ~/svn/_workspace

doc:
    git checkout .
    aifix -l cpp -t write_doc -w ~/svn/_workspace -f {{current_dir}} -f {{current_dir}}/..

fixfail:
    git checkout .
    aifix -l cpp -t fix_code -f {{current_dir}}/target -f {{current_dir}}/..

clean:
    rm -rf {{target_dir}}

