user_name        := env("USER")
current_location := justfile()
current_dir      := justfile_directory()
module_name      := file_name(current_dir)

default: build

build:
    cargo build
    RUST_BACKTRACE=1 cargo test
    cargo clippy

fix:
    git checkout .
    @RUST_BACKTRACE=1 aifix -l rust -t fix_code -f {{current_dir}} -f {{current_dir}}/..

fixd:
    git checkout .
    @RUST_BACKTRACE=1 aifix -d -l rust -t fix_code -f {{current_dir}} -f {{current_dir}}/..

fixws:
    git checkout .
    @RUST_BACKTRACE=1 aifix -l rust -t fix_code -w ~/svn/_workspace -f {{current_dir}} -f {{current_dir}}/.. -f ~/svn/_workspace

doc:
    git checkout .
    @RUST_BACKTRACE=1 aifix -l rust -t write_doc -w ~/svn/_workspace -f {{current_dir}} -f {{current_dir}}/..

fixfail:
    git checkout .
    @RUST_BACKTRACE=1 aifix -l rust -t fix_code -f {{current_dir}}/target -f {{current_dir}}/..

clean:
    @cargo clean -p {{module_name}}

